### PR TITLE
Update schema.json

### PR DESCRIPTION
**Pull request by AlexanderSavenkov**
Some overlooks in Russian translation corrected.

### CODE REVIEW

**Comment by dstillman** [comment]
Thanks, but localization changes need to be made [on Transifex](https://www.transifex.com/zotero/zotero).

**Comment by AlexanderSavenkov** [comment]
> Thanks, but localization changes need to be made [on Transifex](https://www.transifex.com/zotero/zotero).

Sorry, new to this thing. Sent a request to join the Zotero Transifex team. Thanks.

**Comment by AlexanderSavenkov** [comment]
> Thanks, but localization changes need to be made [on Transifex](https://www.transifex.com/zotero/zotero).

@dstillman Dan, thanks again, I spent a few hours yesterday correcting and streamlining the translation. However there are no reviewers / proofreaders in Russian team on Transifex. I'm wondering what to do next for those changes to be accommodated into the next Zotero release. Meanwhile I sent a message to the team coordinator on Transifex.

**Comment by dstillman** [comment]
The changes will be incorporated automatically in an upcoming build.

I also made you a contributor for the locale, since the current contributor doesn't have much time for Zotero these days. Thanks!

**Pull request closed without merging**
